name: CI

on:
  push:
    branches:
      - master
    tags:
      - "v*"
      - '!**-alpha**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: --quiet

      - name: Create Classic Package
        uses: BigWigsMods/packager@v1
        if: ${{ success() && github.event_name != 'pull_request' && contains(github.ref, 'tags/v') }}
        with:
          args: -g classic -w 25391
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

      - name: Create Retail Package
        uses: BigWigsMods/packager@v1
        if: ${{ success() && github.event_name != 'pull_request' && contains(github.ref, 'tags/v') }}
        with:
          args: -w 23628
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

      - name: Create TBC Package
        uses: BigWigsMods/packager@v1
        if: ${{ success() && github.event_name != 'pull_request' && contains(github.ref, 'tags/v') }}
        with:
          args: -g bcc -w 25967
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
